/**
 * Action Handlers - Execute actions recommended by the agent
 * This is the "hands" that performs tasks
 */

class ActionHandlers {
  /**
   * Handle a task generated by the rules engine
   * @param {Object} task - Task to execute
   * @param {Object} userData - User's financial data
   * @returns {Object} - Result of the action
   */
  async handle(task, userData) {
    switch (task.action) {
      case 'set_category_limit':
        return this.setCategoryLimit(task, userData);
      
      case 'suggest_auto_save':
        return this.suggestAutoSave(task, userData);
      
      case 'reserve_for_bill':
        return this.reserveForBill(task, userData);
      
      case 'boost_goal_savings':
        return this.boostGoalSavings(task, userData);
      
      case 'boost_emergency_fund':
        return this.boostEmergencyFund(task, userData);
      
      case 'review_subscriptions':
        return this.reviewSubscriptions(task, userData);
      
      case 'review_large_purchase':
        return this.reviewLargePurchase(task, userData);
      
      case 'celebrate_milestone':
      case 'celebrate_streak':
        return this.celebrate(task, userData);
      
      default:
        return this.defaultHandler(task);
    }
  }

  /**
   * Set spending limit for a category
   */
  async setCategoryLimit(task, userData) {
    const { category, limit } = task.data;
    
    return {
      notify: true,
      type: 'action_required',
      title: `Limit ${category} spending?`,
      message: task.message,
      description: task.description,
      suggestion: task.suggestion,
      actions: [
        {
          label: 'Set Limit',
          value: 'accept',
          primary: true,
          payload: { category, weeklyLimit: Math.round(limit / 4) }
        },
        {
          label: 'Not Now',
          value: 'dismiss',
          primary: false
        }
      ],
      icon: '⚠️',
      color: 'warning'
    };
  }

  /**
   * Suggest enabling auto-save
   */
  async suggestAutoSave(task, userData) {
    const { suggestedSave, autoSaveEnabled } = task.data;
    
    // Don't suggest if already enabled
    if (autoSaveEnabled) {
      return { notify: false };
    }
    
    return {
      notify: true,
      type: 'celebration',
      title: task.message,
      message: task.description,
      description: task.suggestion,
      actions: [
        {
          label: `Save ₹${suggestedSave} Now`,
          value: 'save_now',
          primary: true,
          payload: { amount: suggestedSave }
        },
        {
          label: 'Enable Auto-Save',
          value: 'enable_auto_save',
          primary: false,
          payload: { dailyAmount: 20 }
        },
        {
          label: 'Skip',
          value: 'dismiss',
          primary: false
        }
      ],
      icon: '🎉',
      color: 'success'
    };
  }

  /**
   * Reserve money for upcoming bill
   */
  async reserveForBill(task, userData) {
    return {
      notify: true,
      type: 'reminder',
      title: task.message,
      message: task.description,
      description: task.suggestion,
      actions: [
        {
          label: 'Reserve Money',
          value: 'reserve',
          primary: true,
          payload: { amount: task.data.amount, purpose: task.data.description }
        },
        {
          label: 'Remind Later',
          value: 'snooze',
          primary: false
        }
      ],
      icon: '💡',
      color: 'info'
    };
  }

  /**
   * Boost goal savings
   */
  async boostGoalSavings(task, userData) {
    const { goal, dailyNeeded } = task.data;
    
    return {
      notify: true,
      type: 'goal_alert',
      title: task.message,
      message: task.description,
      description: task.suggestion,
      actions: [
        {
          label: `Save ₹${dailyNeeded * 7} This Week`,
          value: 'add_to_goal',
          primary: true,
          payload: { goalId: goal.id, amount: dailyNeeded * 7 }
        },
        {
          label: 'Extend Deadline',
          value: 'extend_deadline',
          primary: false
        }
      ],
      icon: goal.emoji || '🎯',
      color: 'primary'
    };
  }

  /**
   * Boost emergency fund
   */
  async boostEmergencyFund(task, userData) {
    return {
      notify: true,
      type: 'advice',
      title: task.message,
      message: task.description,
      description: task.suggestion,
      actions: [
        {
          label: 'Add ₹500 Now',
          value: 'add_emergency',
          primary: true,
          payload: { amount: 500 }
        },
        {
          label: 'Save ₹50/Day',
          value: 'enable_daily_save',
          primary: false,
          payload: { dailyAmount: 50, purpose: 'emergency' }
        }
      ],
      icon: '🛡️',
      color: 'warning'
    };
  }

  /**
   * Review subscriptions
   */
  async reviewSubscriptions(task, userData) {
    const { subscriptions, totalCost } = task.data;
    
    return {
      notify: true,
      type: 'advice',
      title: task.message,
      message: task.description,
      description: `Canceling unused ones could save ₹${Math.round(totalCost * 0.3)}/month`,
      actions: [
        {
          label: 'Review Subscriptions',
          value: 'navigate',
          primary: true,
          payload: { route: '/subscription-waste' }
        },
        {
          label: 'Dismiss',
          value: 'dismiss',
          primary: false
        }
      ],
      icon: '📱',
      color: 'info',
      details: subscriptions.map(s => ({
        name: s.description,
        amount: s.amount
      }))
    };
  }

  /**
   * Review large purchase
   */
  async reviewLargePurchase(task, userData) {
    return {
      notify: true,
      type: 'reflection',
      title: task.message,
      message: task.description,
      description: task.suggestion,
      actions: [
        {
          label: 'It Was Planned',
          value: 'confirm_planned',
          primary: true
        },
        {
          label: 'Help Me Budget',
          value: 'adjust_budget',
          primary: false
        }
      ],
      icon: '🤔',
      color: 'neutral'
    };
  }

  /**
   * Celebrate achievements
   */
  async celebrate(task, userData) {
    return {
      notify: true,
      type: 'celebration',
      title: task.message,
      message: task.description,
      description: task.suggestion,
      actions: [
        {
          label: 'Thanks!',
          value: 'dismiss',
          primary: true
        }
      ],
      icon: task.data.milestone ? '🎉' : '🔥',
      color: 'success',
      celebration: true
    };
  }

  /**
   * Default handler
   */
  defaultHandler(task) {
    return {
      notify: true,
      type: 'info',
      title: task.message,
      message: task.description,
      description: task.suggestion,
      actions: [
        {
          label: 'Got it',
          value: 'dismiss',
          primary: true
        }
      ],
      icon: '💡',
      color: 'info'
    };
  }
}

module.exports = new ActionHandlers();
